WebAplikacija/Models/TrenerViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebAplikacija.Models
{
    public class TrenerViewModel
    {
        public int TrenerID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Obrazovanje { get; set; }
        public string ImePrezime { get; set; }
        public string Opis { get; set; }
        public string Slika { get; set; }

    }
}

WebAplikacija/Controllers/GrupaController.cs
using Domen;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NuGet.Versioning;
using PristupPodacima.Jedinica_Posla;
using System.Data;
using WebAplikacija.Models;

namespace WebAplikacija.Controllers
{
    public class GrupaController : Controller
    {
        private readonly IJedinicaPosla jedinicaPosla;
        public GrupaController(IJedinicaPosla jedinicaPosla)
        {
            this.jedinicaPosla = jedinicaPosla;
        }

        public IActionResult Index()
        {
            List<GrupaViewModel> model = jedinicaPosla
                .GrupaRepozitorijum
                .VratiSve()
                .Select(g => new GrupaViewModel
                {
                    GrupaIme = g.GrupaIme,
                    Trener = g.Trener.ImePrezime,
                    Mesto = g.Mesto.Naziv
                })
                .ToList();
            return View(model);
        }

        [Authorize(Roles ="Admin, Trener")]
        public IActionResult IndexAdmin()
        {
            List<GrupaViewModel> model = jedinicaPosla
                .GrupaRepozitorijum
                .VratiSve()
                .Select(g => new GrupaViewModel
                {
                    GrupaID = g.GrupaID,
                    GrupaIme = g.GrupaIme,
                    Trener = g.Trener.ImePrezime,
                    Mesto = g.Mesto.Naziv
                })
                .ToList();
            return View(model);
        }

        public IActionResult Pretrazi(string naziv)
        {
            List<PretraziGrupuViewModel> model = jedinicaPosla
                .GrupaRepozitorijum
                .VratiSve()
                .Select(g => new PretraziGrupuViewModel
                {
                    GrupaIme = g.GrupaIme,
                    TrenerID = g.Trener.TrenerID,
                    Trener = g.Trener.ImePrezime,
                    Mesto = g.Mesto.Naziv
                })
                .ToList();

            List<PretraziGrupuViewModel> nova = new List<PretraziGrupuViewModel>();

            foreach(var item in model)
            {
                if(item.Mesto.Equals(naziv))
                    nova.Add(item);
            }

            
            return View(nova);
        }


        public IActionResult PretraziTrener(int trener)
        {
            List<PretraziGrupuViewModel> model = jedinicaPosla
                .GrupaRepozitorijum
                .VratiSve()
                .Select(g => new PretraziGrupuViewModel
                {
                    GrupaIme = g.GrupaIme,
                    TrenerID = g.Trener.TrenerID,
                    Trener = g.Trener.ImePrezime,
                    Mesto = g.Mesto.Naziv
                })
                .ToList();

            List<PretraziGrupuViewModel> nova = new List<PretraziGrupuViewModel>();

            foreach (var item in model)
            {
                if (item.TrenerID.Equals(trener))
                    nova.Add(item);
            }


            return View(nova);
        }

        [Authorize(Roles = "Admin,Trener")]
        public async Task<IActionResult> Kreiraj()
        {
            KreirajGrupuViewModel model = new KreirajGrupuViewModel();
            model.Treneri = jedinicaPosla.TrenerRepozitorijum
                .VratiSve()
                .Select(g => new SelectListItem
                {
                    Text = g.ImePrezime,
                    Value = g.TrenerID.ToString()
                })
                .ToList();
            model.Mesta = jedinicaPosla.MestoRepozitorijum
                .VratiSve()
                .Select(g => new SelectListItem
                {
                    Text = g.Naziv,
                    Value = g.MestoID.ToString()
                })
                .ToList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Kreiraj(KreirajGrupuViewModel grupa)
        {
            if (ModelState.IsValid)
            {
                Grupa g = new Grupa()
                {
                    GrupaIme = grupa.GrupaIme,
                    TrenerID = grupa.TrenerID,
                    MestoID = grupa.MestoID
                };
                jedinicaPosla.GrupaRepozitorijum.Dodaj(g);
                jedinicaPosla.SacuvajPromene();
                return RedirectToAction("Index");
            }
            return await Kreiraj();
        }


        [Authorize(Roles = "Admin, Trener")]
        public IActionResult Obrisi(int id)
        {
            List<ObrisiGrupuViewModel> list = jedinicaPosla
                .GrupaRepozitorijum
                .VratiSve()
                .Select(g => new ObrisiGrupuViewModel
                {
                    GrupaID = g.GrupaID,
                    GrupaIme = g.GrupaIme,
                    TrenerID = g.TrenerID,
                    MestoID = g.MestoID,
                    Trener = g.Trener.ImePrezime,
                    Mesto = g.Mesto.Naziv

                })
                .ToList();

            ObrisiGrupuViewModel model = list.Single(g => g.GrupaID == id);


            return View(model);
        }

        [HttpPost]
        public IActionResult Obrisi(ObrisiGrupuViewModel model)
        {
            if (ModelState.IsValid)
            {

                Grupa g = new Grupa()
                {
                    GrupaID = model.GrupaID,
                    GrupaIme = model.GrupaIme,
                    TrenerID = model.TrenerID,
                    MestoID = model.MestoID
                };
                jedinicaPosla.GrupaRepozitorijum.Obrisi(g);
                jedinicaPosla.SacuvajPromene();


            }
            return RedirectToAction("Index");
        }

    
    }
}

WebAplikacija/Controllers/TrenerController.cs
using Domen;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PristupPodacima.Jedinica_Posla;
using WebAplikacija.Models;

namespace WebAplikacija.Controllers
{
    public class TrenerController : Controller
    {
        private readonly IJedinicaPosla jedinicaPosla;

        public TrenerController(IJedinicaPosla jedinicaPosla)
        {
            this.jedinicaPosla = jedinicaPosla;
        }
    
        public IActionResult Index()
        {
            List<TrenerViewModel> model = jedinicaPosla
                .TrenerRepozitorijum
                .VratiSve()
                .Select(t => new TrenerViewModel
                {
                    TrenerID = t.TrenerID,
                    Ime = t.Ime,
                    Prezime = t.Prezime,
                    Obrazovanje = t.Obrazovanje.StepenObrazovanja,
                    ImePrezime = t.ImePrezime,
                    Opis = t.Opis,
                    Slika = t.Slika
                })
                .ToList();
            return View(model);
        }

        [Authorize(Roles = "Admin, Trener")]
        public IActionResult IndexAdmin()
        {
            List<TrenerViewModel> model = jedinicaPosla
                .TrenerRepozitorijum
                .VratiSve()
                .Select(t => new TrenerViewModel
                {
                    TrenerID = t.TrenerID,
                    Ime = t.Ime,
                    Prezime = t.Prezime,
                    Obrazovanje = t.Obrazovanje.StepenObrazovanja,
                    Opis = t.Opis,
                    Slika = t.Slika
                })
                .ToList();
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Kreiraj()
        {
            KreirajTreneraViewModel model = new KreirajTreneraViewModel();
            model.Obrazovanja = jedinicaPosla.ObrazovanjeRepozitorijum
                .VratiSve()
                .Select(g => new SelectListItem
                {
                    Text = g.StepenObrazovanja,
                    Value = g.ObrazovanjeID.ToString()
                })
                .ToList();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Kreiraj(KreirajTreneraViewModel trener)
        {
            if (ModelState.IsValid)
            {
                Trener t = new Trener()
                {
                    Ime = trener.Ime,
                    Prezime = trener.Prezime,
                    ObrazovanjeID = trener.ObrazovanjeID,
                    Opis = trener.Opis,
                    Slika = trener.Slika
                };
                jedinicaPosla.TrenerRepozitorijum.Dodaj(t);
                jedinicaPosla.SacuvajPromene();

                return RedirectToAction("Index");
            }
            return await Kreiraj();
        }


        [Authorize(Roles = "Admin")]
        public IActionResult Promeni(int id)
        {

            Trener t = jedinicaPosla.TrenerRepozitorijum.Vrati(id);

            PromeniTreneraViewModel tr = new PromeniTreneraViewModel
            {
                TrenerID = t.TrenerID,
                Ime = t.Ime,
                Prezime = t.Prezime,
                ObrazovanjeID = t.ObrazovanjeID,
                Opis = t.Opis,
                Slika = t.Slika
            };

            tr.Obrazovanja = jedinicaPosla.ObrazovanjeRepozitorijum
                .VratiSve()
                .Select(g => new SelectListItem
                {
                    Text = g.StepenObrazovanja,
                    Value = g.ObrazovanjeID.ToString()
                })
                .ToList();


            return View(tr);
        }

        [HttpPost]
        public IActionResult Promeni(PromeniTreneraViewModel model)
        {
            if (ModelState.IsValid)
            {
                Trener t = new Trener()
                {
                    TrenerID = model.TrenerID,
                    Ime = model.Ime,
                    Prezime = model.Prezime,
                    ObrazovanjeID = model.ObrazovanjeID,
                    Opis = model.Opis,
                    Slika = model.Slika
                };
                jedinicaPosla.TrenerRepozitorijum.Izmeni(t);
                jedinicaPosla.SacuvajPromene();
                return RedirectToAction("Index");

            }
            return Promeni(model.TrenerID);
        }


        [Authorize(Roles = "Admin")]
        public IActionResult Obrisi(int id)
        {
            List<ObrisiTreneraViewModel> list = jedinicaPosla
                .TrenerRepozitorijum
                .VratiSve()
                .Select(t => new ObrisiTreneraViewModel
                {
                    TrenerID = t.TrenerID,
                    Ime = t.Ime,
                    Prezime = t.Prezime,
                    ObrazovanjeID = t.ObrazovanjeID,
                    Obrazovanje = t.Obrazovanje.StepenObrazovanja,
                    Opis = t.Opis,
                    Slika=t.Slika

                })
                .ToList();

            ObrisiTreneraViewModel model = list.Single(t => t.TrenerID == id);


            return View(model);
        }

        [HttpPost]
        public IActionResult Obrisi(ObrisiTreneraViewModel model)
        {
            if (ModelState.IsValid)
            {

                Trener t = new Trener()
                {
                    TrenerID = model.TrenerID,
                    Ime = model.Ime,
                    Prezime = model.Prezime,
                    ObrazovanjeID = model.ObrazovanjeID,
                    Opis = model.Opis,
                    Slika = model.Slika
                };
                jedinicaPosla.TrenerRepozitorijum.Obrisi(t);
                jedinicaPosla.SacuvajPromene();
                

            }
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Pretrazi(string imePrezime)
        {
            List<PretraziTreneraViewModel> model = jedinicaPosla
                .TrenerRepozitorijum
                .VratiSve()
                .Select(t => new PretraziTreneraViewModel
                {
                    TrenerID = t.TrenerID,
                    Ime = t.Ime,
                    Prezime = t.Prezime,
                    ImePrezime = t.ImePrezime,
                    Obrazovanje = t.Obrazovanje.StepenObrazovanja,
                    Opis = t.Opis,
                    Slika = t.Slika
                })
                .ToList();


            PretraziTreneraViewModel? tr = model.FirstOrDefault(t => t.ImePrezime.Trim().ToLower().StartsWith(imePrezime.Trim().ToLower()));

            if (tr == null)
                return RedirectToAction("Index");

            return View(tr);


        }
    }
}

WebAplikacija/Views/Trener/Index.cshtml
@model List<TrenerViewModel>

@using (Html.BeginForm("Pretrazi", "Trener", FormMethod.Post))
{
    @Html.TextBox("imePrezime")
    <br />
    <input type="submit" value="Pretraži" />
}

@foreach (var item in Model)
{
    <div style="background-color: lightslategray; border-radius:5px; width:600px; height:400px; border-bottom-style:solid; border-top-style:solid; border-bottom-color: white; border-top-color: white; margin-top: 20px;">
        <div class="div1">
            <img src="@item.Slika" alt="trener" style="width: 250px; margin-left: 20px;  margin-bottom: 250px; " />
        </div>
        <div class="div2">

            <h3 style="margin-top: 80px; ">@item.ImePrezime</h3>
            <p style="margin-top: 5px;">Obrazovanje: @item.Obrazovanje</p>
            <p style="margin-top: 5px; width:300px ">@item.Opis</p>

            <button style="margin-left: 180px; margin-top: 5px;">
                <a class="nav-link text-dark" asp-area="" asp-route-trener="@item.TrenerID" asp-controller="Grupa" asp-action="PretraziTrener">Grupe</a>
            </button>
            
       </div>

    </div>
    
    
}

WebAplikacija/Views/Trener/IndexAdmin.cshtml
@model List<TrenerViewModel>

<button> <a class="nav-link text-dark" asp-area="" asp-controller="Trener" asp-action="Kreiraj">Kreiraj novog trenera</a> </button>


@foreach (var item in Model)
{
    <div style="background-color: lightslategray; border-radius:5px; width:600px; height:400px; border-bottom-style:solid; border-top-style:solid; border-bottom-color: white; border-top-color: white; margin-top: 20px;">
        <div class="div1">
            <img src="@item.Slika" alt="trener" style="width: 250px; margin-left: 20px;  margin-bottom: 250px; " />
        </div>
        <div class="div2">

            <h3 style="margin-top: 80px; ">@item.ImePrezime</h3>
            <p style="margin-top: 5px;">Obrazovanje: @item.Obrazovanje</p>
            <p style="margin-top: 5px; width:300px ">@item.Opis</p>

            <button style=" margin-top: 5px;">
                <a class="nav-link text-dark" asp-area="" asp-route-trener="@item.TrenerID" asp-controller="Grupa" asp-action="PretraziTrener">Grupe</a>
            </button>
            <button style="margin-top: 5px;">
                <a class="nav-link text-dark" asp-area="" asp-route-id="@item.TrenerID" asp-controller="Trener" asp-action="Promeni">Promeni</a>
            </button>
            <button style="margin-top: 5px;">
                <a class="nav-link text-dark" asp-area="" asp-route-id="@item.TrenerID" asp-controller="Trener" asp-action="Obrisi">Obriši</a>
            </button>

        </div>

    </div>


}

WebAplikacija/Views/Trener/Kreiraj.cshtml
@model KreirajTreneraViewModel
<div asp-validation-summary="All"></div>

<form asp-action="Kreiraj" asp-controller="Trener" method="post">

    <div class="div1">
        <label>Ime:</label>
        <br />
        <label>Prezime:</label>
        <br />
        <label>Obrazovanje:</label>
        <br />
        <label>Opis:</label>
        <br />
        <label>Link slike:</label>
    </div>
    <div class="div2">
        <input type="text" asp-for="Ime" />
        <span asp-validation-for="Ime"></span>
        <br />
        <input type="text" asp-for="Prezime" />
        <span asp-validation-for="Prezime"></span>
        <br />
        <select asp-items="Model.Obrazovanja" asp-for="ObrazovanjeID">
        </select>
        <span asp-validation-for="ObrazovanjeID"></span>
        <br />

        <input type="text" asp-for="Opis" />
        <span asp-validation-for="Opis"></span>
        <br />
        <input type="text" asp-for="Slika" />
        <span asp-validation-for="Slika"></span>
        <br />
    </div>


    <input type="submit" value="Sacuvaj" />

</form>

WebAplikacija/Views/Trener/Obrisi.cshtml
@model ObrisiTreneraViewModel
<div asp-validation-summary="All"></div>

<form asp-action="Obrisi" asp-controller="Trener" method="post">

    <div class="div1">
        <label>Ime:</label>
        <br />
        <label>Prezime:</label>
        <br />
        <label>Obrazovanje:</label>
        <br />
        <label>Opis:</label>
        <br />
        <label>Link slike:</label>
    </div>
    <div class="div2">
        <input type="number" asp-for="TrenerID" hidden />
        <br />
        <input type="text" asp-for="Ime" readonly/>
        <br />
        <input type="text" asp-for="Prezime" readonly/>
        <br />
        <input type="text" asp-for="Obrazovanje" readonly />
        <br />
        <input type="text" asp-for="Opis" readonly />
        <br />
        <input type="Text" asp-for="Slika" readonly />
        <br />
    </div>


    <input type="submit" value="Obriši" />

</form>

WebAplikacija/Views/Trener/Pretrazi.cshtml
@model PretraziTreneraViewModel

<div class="div1" >
    <label>Ime:</label>
    <br />
    <label>Prezime:</label>
    <br />
    <label>Obrazovanje:</label>
    <br />
    <label>Opis:</label>
    <br />
    <br />
    <br />
    <label>Grupe:</label>
    <br />
</div>
<div class="div2" >
    <input type="number" asp-for="TrenerID" hidden />
    <br />
    <input type="text" asp-for="Ime" readonly />
    <br />
    <input type="text" asp-for="Prezime" readonly />
    <br />
    <input type="text" asp-for="Obrazovanje" readonly />
    <br />
    <textarea name="opis" rows="3" cols="30" style=" margin-top:20px; ">
@Model.Opis
    </textarea>
    <br />
    <button style=" margin-bottom: 35px;">
        <a class="nav-link text-dark" asp-area="" asp-route-trener="@Model.TrenerID" asp-controller="Grupa" asp-action="PretraziTrener">Grupe</a>
    </button>
</div>

WebAplikacija/Views/Trener/Promeni.cshtml
@model PromeniTreneraViewModel
<div asp-validation-summary="All"></div>

<form asp-action="Promeni" asp-controller="Trener" method="post">

    <div class="div1">
        <label>Ime:</label>
        <br />
        <label>Prezime:</label>
        <br />
        <label>Obrazovanje:</label>
        <br />
        <label>Opis:</label>
        <br />
        <label>Link slike:</label>
    </div>
    <div class="div2">
        <input type="number" asp-for="TrenerID" hidden/>
        <br />
        <input type="text" asp-for="Ime" />
        <span asp-validation-for="Ime"></span>
        <br />
        <input type="text" asp-for="Prezime" />
        <span asp-validation-for="Prezime"></span>
        <br />
        <select asp-items="Model.Obrazovanja" asp-for="ObrazovanjeID">
        </select>
        <br />
        <input type="text" asp-for="Opis" />
        <br />
        <input type="Text" asp-for="Slika" />
        <br />
    </div>

    <br />

    <input type="submit" value="Sacuvaj" />


</form>