WebAplikacija/Models/KlijentViewModel.cs
namespace WebAplikacija.Models
{
    public class KlijentViewModel
    {

        public int KlijentID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string ImePrezime { get; set; }
        public int Kilaza { get; set; }
        public int Visina { get; set; }
        public string Grupa { get; set; }
        public string Pol { get; set; }

    }
}

WebAplikacija/Controllers/KlijentController.cs
using Domen;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using NuGet.Protocol;
using PristupPodacima.Jedinica_Posla;
using WebAplikacija.Models;

namespace WebAplikacija.Controllers
{
    public class KlijentController : Controller
    {

        private readonly IJedinicaPosla jedinicaPosla;
        private readonly UserManager<User> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        public KlijentController(IJedinicaPosla jedinicaPosla, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.jedinicaPosla = jedinicaPosla;
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            List<KlijentViewModel> model = jedinicaPosla
                .KlijentRepozitorijum
                .VratiSve()
                .Select(k => new KlijentViewModel
                {
                    KlijentID = k.KlijentID,
                    Ime = k.Ime,
                    Prezime = k.Prezime,
                    ImePrezime = k.ImePrezime,
                    Visina = k.Visina,
                    Kilaza = k.Kilaza,
                    Pol = k.Pol.PolNaziv,
                    Grupa = k.Grupa.GrupaIme

                })
                .ToList();
            return View(model);
        }

        public async Task<IActionResult> Kreiraj()
        {
            //User v = new User
            //{
            //    UserName = "tamara",
            //    Email = "tamara@gmail.com",
            //    ImePrezime = "Tamara Tamaric",
            //};

            //var result = await userManager.CreateAsync(v, "Password!123");
            //User v = new User
            //{
            //    UserName = "Nata",
            //    Email = "nata@gmail.com",
            //    ImePrezime = "Nata Natic",
            //};

            //var result = await userManager.CreateAsync(v, "Password!123");

            KreirajKlijentaViewModel model = new KreirajKlijentaViewModel();
            model.Grupe = jedinicaPosla.GrupaRepozitorijum
                .VratiSve()
                .Select(g => new SelectListItem
                {
                    Text = g.GrupaIme + "-" + g.Mesto.Naziv,
                    Value = g.GrupaID.ToString()
                })
                .ToList();
            model.Polovi = jedinicaPosla.PolRepozitorijum
                .VratiSve()
                .Select(p => new SelectListItem
                {
                    Text = p.PolNaziv,
                    Value = p.PolID.ToString()
                })
                .ToList();
            
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Kreiraj(KreirajKlijentaViewModel klijent)
        {
            if (ModelState.IsValid)
            {
                if (klijent.Kilaza == 0)
                {
                    ModelState.AddModelError("Kilaza", "Morate uneti kilazu!");
                    return await Kreiraj();
                }
                if (klijent.Visina == 0)
                {
                    ModelState.AddModelError("Visina", "Morate uneti visinu!");
                    return await Kreiraj();
                }
                Klijent k = new Klijent()
                {
                    Ime = klijent.Ime,
                    Prezime = klijent.Prezime,
                    Kilaza = klijent.Kilaza,
                    Visina = klijent.Visina,
                    PolID = klijent.PolID,
                    GrupaID = klijent.GrupaID
                };
                jedinicaPosla.KlijentRepozitorijum.Dodaj(k);
                jedinicaPosla.SacuvajPromene();
                return RedirectToAction("Index");
            }
            return await Kreiraj();
        }

        [Authorize(Roles = "Trener")]
        public IActionResult Promeni(int id)
        {
            
            Klijent k = jedinicaPosla.KlijentRepozitorijum.Vrati(id);

            PromeniKlijentaViewModel kl = new PromeniKlijentaViewModel
                {
                KlijentID = k.KlijentID,
                Ime = k.Ime,
                Prezime = k.Prezime,
                Visina = k.Visina,
                Kilaza = k.Kilaza,
                PolID = k.PolID,
                GrupaID = k.GrupaID
                };

            kl.Grupe = jedinicaPosla.GrupaRepozitorijum
                .VratiSve()
                .Select(g => new SelectListItem
                {
                    Text = g.GrupaIme + "-" + g.Mesto.Naziv,
                    Value = g.GrupaID.ToString()
                })
                .ToList();
            kl.Polovi = jedinicaPosla.PolRepozitorijum
                .VratiSve()
                .Select(p => new SelectListItem
                {
                    Text = p.PolNaziv,
                    Value = p.PolID.ToString()
                })
                .ToList();

            return View(kl);
        }

        [HttpPost]
        public IActionResult Promeni(PromeniKlijentaViewModel model)
        {
            if (ModelState.IsValid)
            {
                Klijent k = new Klijent()
                {
                    KlijentID = model.KlijentID,
                    Ime = model.Ime,
                    Prezime = model.Prezime,
                    Kilaza = model.Kilaza,
                    Visina = model.Visina,
                    PolID = model.PolID,
                    GrupaID = model.GrupaID
                };
                jedinicaPosla.KlijentRepozitorijum.Izmeni(k);
                jedinicaPosla.SacuvajPromene();
                return RedirectToAction("Index");
            }
            return Promeni(model.KlijentID);
        }


        [Authorize(Roles = "Trener")]
        public IActionResult Obrisi(int id)
        {
            List<ObrisiKlijentaViewModel> list = jedinicaPosla
                .KlijentRepozitorijum
                .VratiSve()
                .Select(k => new ObrisiKlijentaViewModel
                {
                    KlijentID=k.KlijentID,
                    Ime = k.Ime,
                    Prezime = k.Prezime,
                    Visina = k.Visina,
                    Kilaza = k.Kilaza,
                    PolID = k.PolID,
                    Pol = k.Pol.PolNaziv,
                    GrupaID = k.GrupaID,
                    Grupa = k.Grupa.GrupaIme

                })
                .ToList();

            

            ObrisiKlijentaViewModel model = list.Single(k => k.KlijentID == id);

            return View(model);
        }

        [HttpPost]
        public IActionResult Obrisi(ObrisiKlijentaViewModel model)
        {
            if (ModelState.IsValid)
            {

                Klijent k = new Klijent()
                {
                    KlijentID = model.KlijentID,
                    Ime = model.Ime,
                    Prezime = model.Prezime,
                    Kilaza = model.Kilaza,
                    Visina = model.Visina,
                    PolID = model.PolID,
                    GrupaID = model.GrupaID
                };
                jedinicaPosla.KlijentRepozitorijum.Obrisi(k);
                jedinicaPosla.SacuvajPromene();
            }
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Pretrazi(string imePrezime)
        {
            List<PretraziKlijentaViewModel> model = jedinicaPosla
                .KlijentRepozitorijum
                .Pretrazi(imePrezime)
                .Select(k => new PretraziKlijentaViewModel
                {
                    KlijentID = k.KlijentID,
                    Ime = k.Ime,
                    Prezime = k.Prezime,
                    ImePrezime = k.ImePrezime,
                    Visina = k.Visina,
                    Kilaza = k.Kilaza,
                    Pol = k.Pol.PolNaziv,
                    Grupa = k.Grupa.GrupaIme
                })
                .ToList();
            if (model == null)
                return RedirectToAction("Index");

            return View(model);
            
        }

        [Authorize(Roles = "Trener")]

        public async Task<IActionResult> Detalji(int id)
        {
            List<KlijentViewModel> model = jedinicaPosla
                .KlijentRepozitorijum
                .VratiSve()
                .Select(k => new KlijentViewModel
                {
                    KlijentID = k.KlijentID,
                    Ime = k.Ime,
                    Prezime = k.Prezime,
                    ImePrezime = k.ImePrezime,
                    Visina = k.Visina,
                    Kilaza = k.Kilaza,
                    Pol = k.Pol.PolNaziv,
                    Grupa = k.Grupa.GrupaIme
                })
                .ToList();


            KlijentViewModel? kl = model.Single(t => t.KlijentID == id);

            if (kl == null)
                return RedirectToAction("Index");

            return View(kl);


        }

    }
}

WebAplikacija/Views/Klijent/Detalji.cshtml
@model KlijentViewModel


    <div class="div1">
        <label>Ime:</label>
        <br />
        <label>Prezime:</label>
        <br />
        <label>Pol:</label>
        <br />
        <label>Kilaža:</label>
        <br />
        <label>Visina:</label>
        <br />
        <label>Grupa:</label>
    </div>
    <div class="div2">
        <input type="number" asp-for="KlijentID" hidden />
        <br />
        <input type="text" asp-for="Ime" readonly />
        <br />
        <input type="text" asp-for="Prezime" readonly />
        <br />
        <input type="text" asp-for="Pol" readonly />
        <br />
        <input type="number" asp-for="Kilaza" readonly />
        <br />
        <input type="number" asp-for="Visina" readonly />
        <br />
        <input type="text" asp-for="Grupa" readonly />
        <br />
    </div>

    <br />
    <br />

<button style=" margin-left: 43px;"><a class=" nav-link text-dark" asp-area="" asp-route-id="@Model.KlijentID" asp-controller="Klijent" asp-action="Promeni">Promeni</a></button>
<button style=" width: 100px;"><a class="nav-link text-dark" asp-area="" asp-route-id="@Model.KlijentID" asp-controller="Klijent" asp-action="Obrisi">Obriši</a></button>

WebAplikacija/Views/Klijent/Index.cshtml
@model List<KlijentViewModel>

@using (Html.BeginForm("Pretrazi", "Klijent", FormMethod.Post))
{
    @Html.TextBox("imePrezime")
    <br />
    <input type="submit" value="Pretraži" />
}


<table style=" text-align: center;">
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Grupa</th>
            @if (User.IsInRole("Trener")){
                <th></th>
            }
            

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Ime</td>
                <td>@item.Prezime</td>
                <td>@item.Grupa</td>
                @if (User.IsInRole("Trener")){
                    <td><a class="nav-link text-dark" asp-area="" asp-route-id="@item.KlijentID" asp-controller="Klijent" asp-action="Detalji">Detalji</a></td>
                }

                
            </tr>
        }
    </tbody>
</table>

WebAplikacija/Views/Klijent/Kreiraj.cshtml
@model KreirajKlijentaViewModel
<div asp-validation-summary="All"></div>

<form asp-action="Kreiraj" asp-controller="Klijent" method="post">

    <div class="div1">
        <label>Ime:</label>
        <br />
        <label>Prezime:</label>
        <br/>
        <label>Pol:</label>
        <br />
        <label>Kilaža:</label>
        <br />
        <label>Visina:</label>
        <br />
        <label>Odaberi grupu:</label>
    </div>
    <div class="div2">
        <input type="text" asp-for="Ime" />
        <span asp-validation-for="Ime"></span>
        <br/>
        <input type="text" asp-for="Prezime" />
        <span asp-validation-for="Prezime"></span>
        <br />
        <select asp-items="Model.Polovi" asp-for="PolID">
        </select>
        <span asp-validation-for="PolID"></span>
        <br />

        <input type="number" asp-for="Kilaza" />
        <span asp-validation-for="Kilaza"></span>
        <br />
        <input type="number" asp-for="Visina" />
        <span asp-validation-for="Visina"></span>
        <br />
        <select asp-items="Model.Grupe" asp-for="GrupaID">
        </select>
        <span asp-validation-for="GrupaID"></span>
        <br />
    </div>
    

    <input type="submit" value="Sacuvaj" />

</form>

WebAplikacija/Views/Klijent/Obrisi.cshtml
@model ObrisiKlijentaViewModel
<div asp-validation-summary="All"></div>

<form asp-action="Obrisi" asp-controller="Klijent" method="post">

    <div class="div1">
        <label>Ime:</label>
        <br />
        <label>Prezime:</label>
        <br />
        <label>Pol:</label>
        <br />
        <label>Kilaža:</label>
        <br />
        <label>Visina:</label>
        <br />
        <label>Grupa:</label>
    </div>
    <div class="div2">
        <input type="number" asp-for="KlijentID" hidden />
        <br />
        <input type="text" asp-for="Ime" readonly />
        <br />
        <input type="text" asp-for="Prezime" readonly />
        <br />
        <input type="text" asp-for="Pol" readonly />
        <br />
        <input type="number" asp-for="Kilaza" readonly />
        <br />
        <input type="number" asp-for="Visina" readonly />
        <br />
        <input type="text" asp-for="Grupa" readonly />
        <br />
    </div>
    
    <br />

    <input type="submit" value="Obriši" />


</form>

WebAplikacija/Views/Klijent/Pretrazi.cshtml
@model List<PretraziKlijentaViewModel>

@using (Html.BeginForm("Pretrazi", "Klijent", FormMethod.Post))
{
    @Html.TextBox("imePrezime")
    <br />
    <input type="submit" value="Pretraži" />
}


<table style=" text-align: center;">
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Grupa</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Ime</td>
                <td>@item.Prezime</td>
                <td>@item.Grupa</td>
                <td><a class="nav-link text-dark" asp-area="" asp-route-id="@item.KlijentID" asp-controller="Klijent" asp-action="Detalji">Detalji</a></td>
            </tr>
        }
    </tbody>
</table>

WebAplikacija/Views/Klijent/Promeni.cshtml
@model PromeniKlijentaViewModel
<div asp-validation-summary="All"></div>

<form asp-action="Promeni" asp-controller="Klijent" method="post">

    <div class="div1">
        <label>Ime:</label>
        <br />

        <label>Prezime:</label>
        <br />

        <label>Pol:</label>
        <br />

        <label>Kilaža:</label>
        <br />

        <label>Visina:</label>
        <br />

        <label>Odaberi grupu:</label>
    </div>
    <div  class="div2">
        <input type="number" asp-for="KlijentID" hidden />
        <br />
        <input type="text" asp-for="Ime">
        <br />
        <input type="text" asp-for="Prezime" />
        <br />
        <select asp-items="Model.Polovi" asp-for="PolID">
        </select>
        <br />
        <input type="number" asp-for="Kilaza" />
        <br />
        <input type="number" asp-for="Visina" />
        <br />
        <select asp-items="Model.Grupe" asp-for="GrupaID">
        </select>
        <br />
    </div>
    
    <br />

    <input type="submit" value="Sacuvaj" />


</form>